# Generated by Django 2.2.6 on 2019-10-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
                ('status', models.CharField(choices=[{'normal', 'Normal'}, {'Deleted', 'delete'}, {'banned', 'Banned'}, {'vip', 'VIP'}], default='normal', max_length=100, verbose_name='store_status')),
                ('store', models.ManyToManyField(related_name='owners', to='shop.Store', verbose_name='own_stores')),
            ],
            bases=('user.user',),
        ),
    ]
