# Generated by Django 2.2.5 on 2019-09-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=40, verbose_name='slug')),
                ('image', models.ImageField(upload_to='image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongstocom', to='comment.Comments', verbose_name='comment_image')),
                ('product_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongstoimg', to='product.Product', verbose_name='product_image')),
                ('user_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongstouser', to='comment.Comments', verbose_name='user_image')),
            ],
            options={
                'verbose_name': 'images',
            },
        ),
    ]
