# Generated by Django 2.2.4 on 2019-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('deleted', 'Deleted'), ('banned', 'Banned'), ('popular', 'Popular')], db_index=True, default='normal', max_length=10, verbose_name='store_status'),
        ),
    ]
