# Generated by Django 2.2.3 on 2019-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('username', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='username')),
                ('mail', models.EmailField(db_index=True, max_length=200, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('username',),
                'index_together': {('username', 'mail')},
            },
        ),
    ]
