# Generated by Django 2.2.3 on 2019-09-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('username', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='username')),
                ('mail', models.EmailField(db_index=True, max_length=200, unique=True, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=100, unique=True, verbose_name='Telephone')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('username',),
                'index_together': {('username', 'mail')},
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
                ('status_vip', models.CharField(choices=[('vip', 'VIP'), ('not-vip', 'Not VIP')], default='not-vip', max_length=10, verbose_name='status_vip')),
                ('status_user', models.CharField(choices=[('normal', 'Normal'), ('deleted', 'Deleted'), ('banned', 'Banned')], default='normal', max_length=10, verbose_name='status_user')),
                ('recaddress', models.CharField(max_length=100)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_order', to='orders.Order')),
            ],
            options={
                'verbose_name': 'buyer',
                'ordering': ('username',),
            },
            bases=('user.user',),
        ),
    ]
